object Libs {
  private object Versions {
    const val androidX = "1.2.0"
    const val androidXRecyclerView = "1.1.0"
    const val andoridXLifecycle = "2.2.0"
    const val androidXConstraint = "2.0.4"
    const val androidXAnnotations = "1.1.0"
    const val androidMaterial = "1.2.1"
    const val retrofit = "2.9.0"
    const val moshi = "1.11.0"
    const val okhttpLogging = "4.9.0"
    const val anko = "0.10.8"
    const val playServicesMaps = "17.0.0"
    const val lottie = "3.5.0"
    const val activityKtx = "1.2.0-rc01"
    const val koin = "2.2.2"
    const val mpaAndroidChart = "v3.1.0"
    const val likeButton = "0.2.3"
    const val leakcanary = "1.6.2"
    const val timerKt = "1.5.1"
    const val targetTooltip = "2.0.3"
    const val gson = "2.8.6"
    const val swipeRefreshLayout = "1.1.0"
    const val desugaring = "1.1.5"

    // Crashlytics
    const val playServicesFirebaseAnalytics = "18.0.0"
    const val crashlytics = "2.10.1"
  }

  const val kotlinStdlib = "org.jetbrains.kotlin:kotlin-stdlib:${ProjectVersions.kotlin}"
  const val androidX = "androidx.appcompat:appcompat:${Versions.androidX}"
  const val recyclerView = "androidx.recyclerview:recyclerview:${Versions.androidXRecyclerView}"
  const val androidMaterial = "com.google.android.material:material:${Versions.androidMaterial}"
  const val androidXAnnotations = "androidx.annotation:annotation:${Versions.androidXAnnotations}"
  const val constaintLayout = "androidx.constraintlayout:constraintlayout:${Versions.androidXConstraint}"
  const val lifecycleRuntime = "androidx.lifecycle:lifecycle-runtime:${Versions.andoridXLifecycle}"
  const val lifecycleExtensions = "androidx.lifecycle:lifecycle-extensions:${Versions.andoridXLifecycle}"
  const val lifecycleCompiler = "androidx.lifecycle:lifecycle-compiler:${Versions.andoridXLifecycle}"
  const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
  const val retrofitConverterMoshi = "com.squareup.retrofit2:converter-moshi:${Versions.retrofit}"
  const val moshi = "com.squareup.moshi:moshi:${Versions.moshi}"
  const val moshiAdapter = "com.squareup.moshi:moshi-adapters:${Versions.moshi}"
  const val moshiCodegen = "com.squareup.moshi:moshi-kotlin-codegen:${Versions.moshi}"
  const val anko = "org.jetbrains.anko:anko-commons:${Versions.anko}"
  const val googleMaps = "com.google.android.gms:play-services-maps:${Versions.playServicesMaps}"
  const val playServicesLocation = "com.google.android.gms:play-services-location:${Versions.playServicesMaps}"
  const val mpaAndroidChart = "com.github.PhilJay:MPAndroidChart:${Versions.mpaAndroidChart}"
  const val lottie = "com.airbnb.android:lottie:${Versions.lottie}"
  const val likeButton = "com.github.jd-alexander:LikeButton:${Versions.likeButton}"
  const val targetTooltip = "it.sephiroth.android.library.targettooltip:target-tooltip-library:${Versions.targetTooltip}"
  const val activityKtx = "androidx.activity:activity-ktx:${Versions.activityKtx}"
  const val koin = "org.koin:koin-android:${Versions.koin}"
  const val koinScope = "org.koin:koin-androidx-scope:${Versions.koin}"
  const val koinViewModel = "org.koin:koin-androidx-viewmodel:${Versions.koin}"
  const val leakcanary = "com.squareup.leakcanary:leakcanary-android:${Versions.leakcanary}"
  const val leakcanaryFragment = "com.squareup.leakcanary:leakcanary-support-fragment:${Versions.leakcanary}"
  const val leakcanaryNoOp = "com.squareup.leakcanary:leakcanary-android-no-op:${Versions.leakcanary}"
  const val timber = "com.github.ajalt:timberkt:${Versions.timerKt}"
  const val okHttpLogging = "com.squareup.okhttp3:logging-interceptor:${Versions.okhttpLogging}"
  const val swipeRefreshLayout = "androidx.swiperefreshlayout:swiperefreshlayout:${Versions.swipeRefreshLayout}"
  const val desugar = "com.android.tools:desugar_jdk_libs:${Versions.desugaring}"

  const val gson = "com.google.code.gson:gson:${Versions.gson}"

  // Crashlytics
  const val firebaseAnalytics = "com.google.firebase:firebase-analytics:${Versions.playServicesFirebaseAnalytics}"
  const val crashlytics = "com.crashlytics.sdk.android:crashlytics:${Versions.crashlytics}"
}